### ISSUE TITLE
server list not working - undefined method `label' 

### ISSUE THREAD

**Issue by budgester** [chef/knife-rackspace#130]
```
martinstev-ltm1:~ martin.stevens$ knife rackspace server list -VV
INFO: Using configuration from /Users/martin.stevens/.chef/knife.rb
DEBUG: version  (config)
DEBUG: version v2 (cli)
DEBUG: rackspace_api_key ******************** (config)
DEBUG: rackspace_api_key ******************** (cli)
DEBUG: rackspace_username  (config)
DEBUG: rackspace_username  (cli)
DEBUG: rackspace_api_username ********** (config)
DEBUG: rackspace_api_username  (cli)
DEBUG: rackspace_auth_url  (config)
DEBUG: rackspace_auth_url  (cli)
DEBUG: rackspace_auth_url https://identity.api.rackspacecloud.com/v2.0 (using)
DEBUG: rackspace_region LON (config)
DEBUG: rackspace_region LON (cli)
DEBUG: rackspace v2
DEBUG: https_proxy <not specified> (config)
DEBUG: http_proxy <not specified> (config)
DEBUG: using proxy <none> (config)
DEBUG: ssl_verify_peer false (config)
/Users/martin.stevens/.chefdk/gem/ruby/2.3.0/gems/knife-rackspace-1.0.0/lib/chef/knife/rackspace_server_list.rb:42:in `block in run': undefined method `label' for #<Fog::Compute::RackspaceV2::Image:0x007ffb78273690> (NoMethodError)
	from /Users/martin.stevens/.chefdk/gem/ruby/2.3.0/gems/knife-rackspace-1.0.0/lib/chef/knife/rackspace_server_list.rb:42:in `collect'
	from /Users/martin.stevens/.chefdk/gem/ruby/2.3.0/gems/knife-rackspace-1.0.0/lib/chef/knife/rackspace_server_list.rb:42:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:58:in `load'
	from /usr/local/bin/knife:58:in `<main>'
```

**Comment by budgester** [comment]
The following all work
knife rackspace flavor list
knife rackspace network list
knife rackspace image list
